version: '3.8'
services:
    nginx:
        build: docker/nginx
        command: nginx -g "daemon off;"
        links:
            - backend
        ports:
            - "8090:80"
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - backend

    backend:
        build: docker/php
        volumes:
            - ./backend:/var/www/html
        depends_on:
            - db
        working_dir: /var/www/html
        command: php-fpm
        ports:
            - "9000:9000"
        links:
            - db

    db:
        image: mysql:8
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - "3333:3306"
        environment:
            MYSQL_DATABASE: test-app
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - dbdata:/var/lib/mysql

    frontend:
        build:
            context: .
            dockerfile: docker/node/Dockerfile
        volumes:
            - ./frontend:/app
            - /app/node_modules
        ports:
            - "3000:3000"

volumes:
    dbdata:
